import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className='flex container bg-slate-100 h-screen mx-auto'>
      <Head>
        <title className='text-5xl font-bold'>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div className="flex bg-hero-home bg-center h-[481px] w-full justify-center py-2">
            <p className='font-thin text-3xl'>Meow</p>
        </div>
    </div>
  )
}

export default Home
